package com.example.data.remote

import android.content.Context
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import androidx.credentials.exceptions.GetCredentialCancellationException
import androidx.credentials.exceptions.GetCredentialException
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.android.libraries.identity.googleid.GoogleIdTokenParsingException
import com.google.firebase.auth.AuthResult
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.FirebaseUser
import com.google.firebase.auth.GoogleAuthProvider
import com.google.firebase.database.FirebaseDatabase
import kotlinx.coroutines.tasks.await
import java.security.MessageDigest
import java.util.UUID

class GoogleAuthClient(
    private val context: Context,
    private val auth: FirebaseAuth = FirebaseAuth.getInstance()
) {
    private val credentialManager = CredentialManager.create(context)

    fun getServerClientId(): String {
        // First try to read default_web_client_id generated by Google Services plugin if present
        val resId = context.resources.getIdentifier("default_web_client_id", "string", context.packageName)
        if (resId != 0) {
            val resClientId = context.getString(resId)
            if (resClientId.isNotBlank()) return resClientId
        }
        // Web Client ID (client_type 3) from Firebase project 412324660500 (drigo-2a3a3)
        return "412324660500-kq6daqp5pfg7mrp7ta9d4l33so1g1r4s.apps.googleusercontent.com"
    }

    suspend fun signInWithGoogle(customServerClientId: String? = null): Result<FirebaseUser?> {
        val serverClientId = customServerClientId ?: getServerClientId()

        return try {
            val rawNonce = UUID.randomUUID().toString()
            val bytes = rawNonce.toByteArray()
            val md = MessageDigest.getInstance("SHA-256")
            val digest = md.digest(bytes)
            val hashedNonce = digest.fold("") { str, it -> str + "%02x".format(it) }

            val googleIdOption = GetGoogleIdOption.Builder()
                .setFilterByAuthorizedAccounts(false)
                .setServerClientId(serverClientId)
                .setAutoSelectEnabled(false)
                .setNonce(hashedNonce)
                .build()

            val request = GetCredentialRequest.Builder()
                .addCredentialOption(googleIdOption)
                .build()

            val result = credentialManager.getCredential(
                request = request,
                context = context
            )

            val credential = result.credential
            if (credential is CustomCredential && credential.type == GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL) {
                val googleIdTokenCredential = GoogleIdTokenCredential.createFrom(credential.data)
                val idToken = googleIdTokenCredential.idToken
                
                val firebaseCredential = GoogleAuthProvider.getCredential(idToken, null)
                val authResult: AuthResult = auth.signInWithCredential(firebaseCredential).await()
                val user = authResult.user

                // Persist/Update user profile in Firebase Realtime Database
                user?.let { u ->
                    syncUserToRealtimeDatabase(u)
                }

                Result.success(user)
            } else {
                Result.failure(Exception("Unexpected credential type received: ${credential::class.java.name}"))
            }
        } catch (e: GetCredentialCancellationException) {
            Result.failure(Exception("Sign in cancelled by user"))
        } catch (e: GetCredentialException) {
            Result.failure(Exception("Google Sign-In failed: ${e.localizedMessage ?: e.message}"))
        } catch (e: GoogleIdTokenParsingException) {
            Result.failure(Exception("Invalid Google ID token response"))
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    suspend fun syncUserToRealtimeDatabase(user: FirebaseUser) {
        try {
            val uid = user.uid
            val userRef = FirebaseDatabase.getInstance().getReference("users").child(uid)
            val userData = mapOf(
                "uid" to uid,
                "name" to (user.displayName ?: "Drigo User"),
                "email" to (user.email ?: ""),
                "photoUrl" to (user.photoUrl?.toString() ?: ""),
                "provider" to "google",
                "lastLoginAt" to System.currentTimeMillis()
            )
            userRef.updateChildren(userData).await()
        } catch (_: Exception) {
            // Non-blocking sync
        }
    }
}
